select A.PRODUCT_ID, A.PRODUCT_NAME, sum(A.PRICE * B.AMOUNT) as TOTAL_SALES
from FOOD_PRODUCT A join FOOD_ORDER B on A.PRODUCT_ID = B.PRODUCT_ID
where year(B.PRODUCE_DATE) = 2022 and month(B.PRODUCE_DATE) = 5
group by A.PRODUCT_ID
order by TOTAL_SALES desc, A.PRODUCT_ID