SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO AS A
         JOIN (SELECT ITEM_TREE.ITEM_ID
               FROM ITEM_TREE JOIN ITEM_INFO ON ITEM_TREE.PARENT_ITEM_ID = ITEM_INFO.ITEM_ID
               WHERE ITEM_INFO.RARITY = 'RARE') AS B ON A.ITEM_ID = B.ITEM_ID
ORDER BY ITEM_ID DESC