SELECT A.YEAR, B.MAX_SIZE_OF_COLONY - A.SIZE_OF_COLONY AS YEAR_DEV, A.ID
FROM (
         SELECT ID, PARENT_ID, SIZE_OF_COLONY, YEAR(DIFFERENTIATION_DATE) AS YEAR
         FROM ECOLI_DATA
     )AS A
         JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR
) AS B
              ON A.YEAR = B.YEAR
ORDER BY YEAR, YEAR_DEV